// <auto-generated />
namespace Eclerx.Question3.Anshuman.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterSupplierTableSecond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterSupplierTableSecond));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281058282_AlterSupplierTableSecond"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
